Algoritmo "crescente"

Var

x,y : inteiro

Inicio

     escreval("Digite dois numeros")
     leia(x)
     leia(Y)
     
     enquanto x <> y faca
     
     se x < Y entao
        escreval("crescente")
     senao
          escreval("decrescente")
     fimse
     
     escreval("digite outros dois números")
     leia(x)
     leia(y)
     
     fimenquanto



Fimalgoritmo